### ISSUE TITLE
ハンバーガーメニューの Contact が機能していない

### ISSUE THREAD

**Issue by mapconcierge** [dronebird/www_dronebird_org#5]
おそらく Mailto 設定が正しくないと思われます。

**Comment by wdolphin** [comment]
### Google Form を使ってDronebird のcontact にして、Dronebird のWebに実装する。
* どのGoogle account（Gmail）を使ってフォームを作るか決める必要があります。
個人メルアドでテストしてローカルでは動作しました。下の図のような感じです。
* 簡単なcontact.htmlをつくりました。（FormができたらこれをGithubにアップロードする必要があります。）

![dronebird_contact](https://user-images.githubusercontent.com/15658355/120588115-9845ec80-c471-11eb-987c-341d098980fc.png)

1. Google Form で　CONTACT form をつくる
[googleform](https://www.google.com/intl/ja_jp/forms/about/)
参考になったサイト
https://tonari-it.com/create-google-form/
https://souken-blog.com/2019/05/28/gogle-form/
連絡が来た時にメールで通知を受け取るために：
フォーム作成中に上の送信の右横三つの点をクリック→新しい回答についてのメールを受け取るにチェックを入れる　
![notice](https://user-images.githubusercontent.com/15658355/120587647-b6f7b380-c470-11eb-893b-ac3ceba9a7b4.png)

2. フォーム ができたらiframe をコピーする。
今　contact.html の　26行目に入っている<iframe src=://…></iframe)部分を削除して、コピーしたiframeを挿入する。width=”100%”にする
3. Dronebird websiteのindex.htm 84行目のCONTACTをcontact.htmlとリンクする。
4.  contact.htmlをアップロードする。
5. Dronebird website のハンバーガーメニューCONTACTをクリックすると、contact.htmlに飛びGoogleformがでてくるはずです。

**Comment by wdolphin** [comment]
pull request したことありませんが、contact.htmlだけのpull request できるのですか？
